#!/bin/zsh
export TOS_MNT_ROOT="/mnt/team_of_six"
export TOS_BIN="$TOS_MNT_ROOT/.local/bin"
export TOS_CONF="$TOS_MNT_ROOT/.local/conf"

if [[ -n "$SUDO_USER" ]]; then
    export TOS_IPC="$TOS_MNT_ROOT/tos_home/$SUDO_USER/.ipc"
    export TOS_SANDBOX="$TOS_MNT_ROOT/tos_home/$SUDO_USER/sandbox"
    
    export TOS_INPUT="$TOS_IPC/inbox.md"
    export TOS_CONTEXT="$TOS_IPC/outbox.md"
fi
